version: '3'

# Deletes under vendor when mounting, Specify another volume
# If you edit Gopkg.toml, also delete the vendor volume and rebuild(`dep ensure`) the image
volumes:
  vendor:

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    volumes:
      - ./src/api:/go/src/api
      - vendor:/go/src/api/vendor
    command: realize start --run
    ports:
      - 3001:3001
      - 2345:2345
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
