
[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.1"

[[constraint]]
  name = "github.com/caarlos0/env"
  version = "6.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/fvbock/endless"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.5.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.5.0"

[prune]
  go-tests = true
  unused-packages = true
